### ISSUE TITLE
Width of pictures

### ISSUE THREAD

**Issue by merlijnkersten** [merlijnkersten/merlijnkersten.github.io#3]
Change width of pictures: how? stylesheet?

**Comment by fonsp** [comment]
👉🖼 [https://stackoverflow.com/a/14747656/2079386](https://stackoverflow.com/a/14747656/2079386)

**Comment by merlijnkersten** [comment]
merci (: dan moet ik alleen al mijn tags herdoen (dus issue voor later haha)

**Comment by merlijnkersten** [comment]
Fixed: set max-width of web page in CSS
